CREATE TABLE Hospital_Latter (
	    SEQ NUMBER(5) PRIMARY KEY,
	    WDATE DATE NOT NULL,
	    CONTENT VARCHAR2(1000) NOT NULL,
	    WRITER_ID VARCHAR2(15) NOT NULL,
	    USER_ID VARCHAR2(15) NOT NULL,
	    ISREAD NUMBER(1) NOT NULL,
	    RECEIVE_DEL NUMBER(1) NOT NULL,
	    SEND_DEL NUMBER(1) NOT NULL
	);
	
DROP TABLE Hospital_Latter
CASCADE CONSTRAINT;
	
SELECT * FROM Hospital_Latter

CREATE SEQUENCE Hospital_Latter_SEQ
START WITH 1 INCREMENT BY 1;

DROP SEQUENCE Hospital_Latter_SEQ;

ALTER TABLE Hospital_Latter
ADD CONSTRAINT Hospital_Latter_USER_ID_FK FOREIGN KEY(USER_ID)
REFERENCES MEMBER(ID)
ADD CONSTRAINT Hospital_Latter_WRITER_ID_FK FOREIGN KEY(WRITER_ID)
REFERENCES MEMBER(ID);

alter table Hospital_Latter drop CONSTRAINT Hospital_Latter_USER_ID_FK
alter table Hospital_Latter drop CONSTRAINT Hospital_Latter_WRITER_ID_FK


INSERT INTO Hospital_Latter (SEQ,WDATE,CONTENT,WRITER_ID,USER_ID,ISREAD,RECEIVE_DEL,SEND_DEL) 
	VALUES(Hospital_Latter_SEQ.NEXTVAL,SYSDATE,'안녕하세요','진라면','1234',0,0,0);
	
SELECT SEQ,WDATE,WRITER_ID,CONTENT,DEL,ISREAD 
FROM (SELECT SEQ,USER_ID,WRITER_ID,CONTENT,WDATE,ISREAD,DEL 
		FROM Hospital_Latter
		WHERE USER_ID = '1234'
		ORDER BY WDATE DESC)
WHERE ROWNUM<= 10